name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy-s3:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-s3.yml
    secrets: inherit

  docker:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker-ecr.yml
    secrets: inherit

  deploy-ec2:
    needs: docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-ec2.yml
    with:
      image_tag: ${{ needs.docker.outputs.image_tag }}
    secrets: inherit
